name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        echo $HOME
        echo $GITHUB_EVENT_PATH
        find $HOME
        echo Coucou > $GITHUB_EVENT_PATH/coucou
    
    - name: Print another greeting
      env:
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        set
        cat $GITHUB_EVENT_PATH/coucou




