name: Testing the flist publisher
on: push

jobs:
  my-job:
    name: Publishing flist
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Publishing flist
      uses: maxux/publish-flist@master
      with:
        action: publish
        name: demo-from-action.flist
        token: ${{ secrets.HUB_TOKEN }}

    - name: Promoting flist
      uses: maxux/publish-flist@master
      with:
        action: promote
        user: tf-official-apps
        name: maxux/demo-from-action.flist
        target: demo-action-promoted.flist
        token: ${{ secrets.HUB_TOKEN }}

    - name: Symlink flist
      uses: maxux/publish-flist@master
      with:
        action: symlink
        user: tf-official-apps
        name: demo-action-promoted.flist
        target: final:symlinked-master.flist
        token: ${{ secrets.HUB_TOKEN }}
