name: Greeting from Mona

on: push

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@master

    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Mona
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        mkdir $HOME/workdir
        echo Coucou > $HOME/workdir/hello
    
    - name: Print another greeting
      env:
        MIDDLE_NAME: The
        LAST_NAME: Octocat
      run: |
        set
        cat $HOME/workdir/hello

    - name: And use external one
      uses: maxux/publish-flist@master
      with:
        name: demo-from-action.flist
        token: ${{ secrets.HUB_TOKEN }}
